baseURL = 'https://reg-blog.com/'
languageCode = 'en-us'
title = 'REG Blog'
googleAnalytics = "G-TKGQXYBKE4"

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"
  env = "PUBLIC"

[taxonomies]
  category = "categories"
  author = "authors"