baseURL = 'https://reg-blog.com/'
languageCode = 'en-us'
title = 'REG Blog'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"