name: Update Blog with AWS News
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Update to v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Update to v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate new blog post
        run: python generate_post.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add content/*
          git commit -m "Add new AWS news post"
          git push
