name: Latest REG Blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest REG Blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "REGBLOG"
          feed_list: "https://www.reg-blog.com/index.xml"
          commit_message: "Update reg-blog.com blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
